### ISSUE TITLE
Tabby chat 2 startup error

### ISSUE THREAD

**Issue by Kylebartaous** [killjoy1221/TabbyChat-2#85]
Mine craft version: 1.11.2

Mine craft forge build: forge-13.20.1.2513 w/ lite loader mix in's

Tabby chat version: mod-tabbychat-2-2.1.6-mc1.11.2.lite mod

Mmm Utils version: lib-mnmutils-1.3.1-mc1.11.2.lite mod

Crash log: https://pastebin.com/yn2FxhyE

Log latest log: https://pastebin.com/K64YkdQj

Lite loader log: https://pastebin.com/gk3SGDZt

So after re finding this mod to use i found a problem with it, After the launcher mine craft to the main title screen i am seeing a start up error in the lite loader tab to the right about tabby chat 2, then i tried to remove & reinstall tabby chat 2 + it's core mod it still happen to get the error. I have also tried to make a new profile w/ using the same latest forge version & resetting up lite loader each time on the twitch app w/ tabby chat and other mod only copied over and leaving option setting and config to get re-gened, also seems to still happen.

http://prntscr.com/gyq2n6

& with in the lite loader tab it giving me the info that it error from witch is

http://prntscr.com/gyq3e7

java.lang.NoSuchMethodError: mnm.mods.tabbychat.gui.ChatTray.getParent()Lmnm/mods/util/gui/GuiPanel;
   at mnm.mods.tabbychat.gui.ChatTray.updateComponent(ChatTray.java:55)
   at mnm.mods.util.gui.GuiPanel$$Lambda$175/99552379.accept(Unknown Source)
   at java.util.ArrayList.forEach(ArrayList.java:1249)
   at mnm.mods.util.gui.GuiPanel.updateComponent(GuiPanel.java:105)
   at mnm.mods.tabbychat.gui.ChatBox.<init>(ChatBox.java:44)
   at mnm.mods.tabbychat.ChatManager.<init>(ChatManager.java:71)
   at mnm.mods.tabbychat.TabbyChat.postInit(TabbyChat.java:130)
   at mnm.mods.tabbychat.liteloader.LiteModTabbyChat.onInitCompleted(LiteModTabbyChat.java:45)
   at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.onStartupComplete(LiteLoaderEventBrokerClient.java:283)
   at net.minecraft.client.Minecraft.handler$onStartupComplete$zzi000(Minecraft.java:3236)
   at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:556)
   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
   at net.minecraft.client.main.Main.main(SourceFile:124)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:483)
   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Kylebartaous** [comment]
After some testing of just having tabby chat 2 & its core mod in its own profile only I am still getting the 1 mod startup error so it most be your mod having a problem , also tried having it loaded with some mods and same.

**Comment by killjoy1221** [comment]
Looks like I archived the wrong version on curse. Go ahead and download `2.2.1-mc1.11.2`

**Comment by Kylebartaous** [comment]
thx
