### ISSUE TITLE
Mixins Issue

### ISSUE THREAD

**Issue by CDAGaming** [killjoy1221/TabbyChat-2#95]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiSleepMP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_162]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_162]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more

Crashing on Load Lately with this issue, once I add TabbyChat to my mods

**Comment by killjoy1221** [comment]
Please provide a full log of the game. Also include other mods you are using and their versions.

**Comment by CDAGaming** [comment]
Ok, will send the full log once I'm home

**Comment by CDAGaming** [comment]
Found Issue, was my own fault, closing
